# configs/FINDER.yaml

algorithm:
  type: DQN
  model_cfg:
    type: Qnet
    backbone_cfg:
      type: GraphSAGE
      in_channels: 1
      hidden_channels: 64
      num_layers: 3
    q_head_cfg:
      type: QHead
      in_channels: 128
  optimizer_cfg:
    type: AdamW
    lr: 0.001
    weight_decay: 0.0005
  replaybuffer_cfg:
    type: ReplayBuffer
    capacity: 10000
    n_step: 5
    prioritized: False
  scheduler_cfg:
    type: "LinearLR"
    start_factor: 1
    end_factor: 0.01
    total_iters: 1000
  metric_manager_cfg:
    metrics:
      - type: AUC
        record: min
      - type: AttackRate
        record: min
  algo_cfg:
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 10000
    tau: 0.005
  device: cuda

environment:
  type: NetworkDismantlingEnv
  node_features: degree
  node_dim: 1
  synth_type: ba
  synth_args:
    min_n: 30
    max_n: 50
    m: 4
  is_undirected: True
  value_type: auc
  use_component: False
  device: cuda

training:
  seed: 42
  use_gcc: False
  num_episodes: 1000
  batch_size: 32
  max_steps: 10000
  log_interval: 10
  save_interval: 100

test:
  seed: 42
  data_dir: .\data\small
  use_gcc: True
