[project]
name = "centrilearn"
version = "v0.2.0"
description = "CentriLearn: A Reinforcement Learning Framework for Complex Networks Tasks"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "CentriLearn Team"}
]
keywords = ["reinforcement-learning", "graph-neural-networks", "network-dismantling"]

dependencies = [
    "torch>=2.7.0",
    "torch-geometric>=2.6.0",
    "torch-scatter>=2.1.0",
    "networkx>=3.4.0",
    "numpy>=2.2.5",
    "pandas>=2.0.0",
    "scipy>=1.13.0",
    "pyyaml>=6.0.0",
]

[tool.uv]
prerelease = "allow"

[tool.uv.extra-build-dependencies]
torch-scatter = ["torch"]

[tool.setuptools]
packages = ["centrilearn"]

[project.urls]
Homepage = "https://github.com/He-JiYe/CentriLearn"
Documentation = "https://github.com/He-JiYe/CentriLearn#readme"
Repository = "https://github.com/He-JiYe/CentriLearn.git"
Issues = "https://github.com/He-JiYe/CentriLearn/issues"
